services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - zotsport-network

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    environment:
      - DATABASE_PATH=/data/education.db
    volumes:
      - ./db:/data
    ports:
      - "3001:3000"
    networks:
      - zotsport-network

  redis:
    image: redis:alpine
    command: redis-server --requirepass secret
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - zotsport-network

  proxy:
    build:
      context: ./proxy
      dockerfile: ../docker/proxy/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - zotsport-network

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "9000:9000"
    networks:
      - zotsport-network

  check_db:
    build:
      context: ./docker/sqlite
    volumes:
      - ./db:/data
    networks:
      - zotsport-network
    command: ["sh", "/check_db.sh"]

networks:
  zotsport-network:
    driver: bridge

volumes:
  redis-data:
  portainer-data: